name: fingerprint_auth_example
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2  
  barcode_widget: ^2.0.1
  cupertino_icons: ^1.0.8   # Latest as of 2025
  local_auth: ^2.3.0        # Dart 3 & null safety compatible
  pdf: ^3.10.7
  printing: ^5.13.0
  barcode: ^2.2.4
  flutter_secure_storage: ^9.0.0
  # screenshot: 1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
